### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelections' of undefined

### ISSUE THREAD

**Issue by pboutin44** [mmattozzi/atom-base64#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.1
**Thrown From**: [base64](https://github.com/mmattozzi/atom-base64) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelections' of undefined

```
At /Users/pboutin/.atom/packages/base64/lib/base64.coffee:19

TypeError: Cannot read property 'getSelections' of undefined
    at Object.decode (/packages/base64/lib/base64.coffee:19:24)
    at /packages/base64/lib/base64.coffee:6:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/zz/zyxvpxvq6csfxvn_n0001t4h000fj4/T/AppTranslocation/8699BBBD-E0DE-4860-AC4F-C53B50DB95A7/d/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/private/var/folders/zz/zyxvpxvq6csfxvn_n0001t4h000fj4/T/AppTranslocation/8699BBBD-E0DE-4860-AC4F-C53B50DB95A7/d/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/private/var/folders/zz/zyxvpxvq6csfxvn_n0001t4h000fj4/T/AppTranslocation/8699BBBD-E0DE-4860-AC4F-C53B50DB95A7/d/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/private/var/folders/zz/zyxvpxvq6csfxvn_n0001t4h000fj4/T/AppTranslocation/8699BBBD-E0DE-4860-AC4F-C53B50DB95A7/d/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/private/var/folders/zz/zyxvpxvq6csfxvn_n0001t4h000fj4/T/AppTranslocation/8699BBBD-E0DE-4860-AC4F-C53B50DB95A7/d/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 23x -0:57.6.0 core:move-down (input.hidden-input)
 15x -0:57.5.0 core:move-up (input.hidden-input)
 80x -0:56.1.0 core:move-down (input.hidden-input)
 59x -0:47.1.0 core:move-up (input.hidden-input)
     -0:37.2.0 base64:encode (input.hidden-input)
     -0:33.8.0 base64:decode (input.hidden-input)
  2x -0:27.1.0 core:select-all (input.hidden-input)
     -0:17.1.0 base64:encode (input.hidden-input)
  2x -0:17.1.0 base64:decode (input.hidden-input)
```

### Non-Core Packages

```
base64 0.3.0 
```

**Comment by mmattozzi** [comment]
Hi, I'm having trouble reproducing this... where were you in the editor or what were you doing that led to this error? Thanks!

**Comment by gitVimaco** [comment]
Hi, I reproduced this opening a png image and trying to encode it in base64. Hope it helps. I'd be great to be able to encode and decode binary files.

**Comment by mmattozzi** [comment]
That's a really interesting idea, it's certainly not something this package supports today (so I made a commit to disallow invoking this package on non-Text frames). If I did add support for this (somehow) would it make sense to copy the resulting base64 text to the clipboard? I don't think it would make sense to mangle the source image.
